spring:
    datasource:
        url: jdbc:postgresql://localhost:3002/postgres
        username: postgres
        password: password

server:
    port: 3001
    ssl:
        key-store: classpath:cert/springboot.p12
        key-store-password: password
        key-store-type: PKCS12
        key-alias: springboot
        key-password: password
        enabled: true