spring:
    datasource:
        url: jdbc:postgresql://localhost:3002/postgres
        username: postgres
        password: password
    jpa:
        properties.hibernate.enable_lazy_load_no_trans: true
    jackson:
        default-property-inclusion: NON_NULL

server:
    port: 3001
    ssl:
        key-store: classpath:cert/springboot.p12
        key-store-password: password
        key-store-type: PKCS12
        key-alias: springboot
        key-password: password
        enabled: true

logging:
    level:
        tournament: DEBUG

resolve.delay.seconds: 10
start.delay.seconds: 1
user.admins: jake.baumbaugh@gmail.com